"""First Migration

Revision ID: 9a7b2eb176a2
Revises: c248b0eb9517
Create Date: 2023-04-06 14:09:29.497322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a7b2eb176a2'
down_revision = 'c248b0eb9517'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
